# -*- coding: utf-8 -*-
"""algo4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11qA2Oqn1HaV1PRDcoBDq9R5b9ob6vxIH
"""

print('@@@@      @     @@@@ @     @')
print('@  @     @ @    @    @     ')
print('@ @     @   @   @@@@ @     @  ')
print('@  @   @ @@@ @  @    @     @   ')
print('@   @ @       @ @    @@@@@ @      ')

def decimal_to_binary(decimal):
    binary = bin(decimal)
    return binary[2:]  # Menghilangkan "0b" di awal hasil biner

def binary_to_decimal(binary):
    decimal = int(binary, 2)
    return decimal

while True:
    print("----PROGRAM KONVERSI BILANGAN----")
    print("     1-> Angka ke Biner")
    print("     2-> Biner ke angka")
    print("     3-> Exit")

    choice = input("Masukan Pilihan Anda-> ")

    if choice == '1':
        decimal_input = int(input("Masukkan Angka: "))
        binary_output = decimal_to_binary(decimal_input)
        print(f"Angka: {binary_output}")
    elif choice == '2':
        binary_input = input("Masukkan biner: ")
        decimal_output = binary_to_decimal(binary_input)
        print(f"Biner: {decimal_output}")
    elif choice == '3':
        print("---Terima Kasih---")
        break
    else:
        print("Pilihan tidak valid. Silakan coba lagi.")

def cek_angka_genap(lst):
    for angka in lst:
        if angka % 2 == 0:
            return True
    return False

input_str = input("Masukkan list angka (integer)-> ")
angka_list = [int(x) for x in input_str.split()]

hasil = cek_angka_genap(angka_list)

if hasil:
    print("List memiliki angka genap.")
else:
    print("List tidak memiliki angka genap.")